Repository asyncapi/cli, pull requests merged in 2022-02, with the labels that each got.

#135 feat: integrate `asyncapi diff` library using the `diff` command
  package-lock.json
  package.json
  scripts/fetch-asyncapi-example.js
  src/commands/diff.ts
  src/errors/diff-error.ts
  src/models/Context.ts
  test/commands/context.test.ts
  test/commands/diff.test.ts
  test/fixtures/invalid-overrides.json
  test/fixtures/overrides.json
  test/fixtures/specification_v1.yml
  test/fixtures/specification_v2.yml
Labels: autoapproved, ready-to-merge

#178 fix: improve `validation-error.ts` file
  src/errors/validation-error.ts
Labels: autoapproved, ready-to-merge

#174 fix: show correct error message when no context is saved
  src/commands/validate.ts
  src/errors/context-error.ts
  src/errors/specification-file.ts
  src/models/SpecificationFile.ts
  test/commands/validate.test.ts
Labels: autoapproved, ready-to-merge

#230 docs: fix missing toc
  README.md
Labels: ready-to-merge

#220 feat: add global specification watcher
  src/commands/diff.ts
  src/commands/validate.ts
  src/flags.ts
  src/globals.ts
  test/commands/validate.test.ts
Labels: ready-to-merge, do-not-merge

#212 feat: added testing for new
  src/commands/new.ts
  test/commands/new.test.ts
  test/testHelper.ts
Labels: ready-to-merge
