Repository asyncapi/cli, pull requests merged in 2023-02, with the labels that each got.

#414 docs: new docs folder created to host the docs for AsyncAPI CLI
  README.md
  docs/index.md
  docs/installation.md
  docs/usage.md
Labels: ready-to-merge, autoupdate

#397 feat: add optimize command
  README.md
  docs/usage.md
  package-lock.json
  package.json
  src/commands/optimize.ts
  test/commands/optimize.test.ts
  test/dummyspec/unoprimizedSpec.yml
  test/specification-invalid.yml
Labels: ready-to-merge

#454 fix: bump @asyncapi dependencies to the latest versions
  package-lock.json
  package.json
  test/valid-specification.yml
Labels: bug, ready-to-merge

#458 fix: solve typescript models generation error and some failing tests
  .gitignore
  package-lock.json
  src/commands/generate/models.ts
  test/commands/convert.test.ts
  test/commands/generate/fromTemplate.test.ts
  test/commands/generate/models.test.ts
  test/commands/optimize.test.ts
  test/commands/validate.test.ts
  test/testHelper.ts
Labels: ready-to-merge
